# Generated by Django 2.2.5 on 2020-02-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('publisher_id', models.ForeignKey(on_delete=True, to='app01.Publisher')),
            ],
        ),
    ]
