# Generated by Django 2.2.5 on 2020-02-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200208_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('agg', models.IntegerField()),
                ('book', models.ManyToManyField(to='app01.Book')),
            ],
        ),
    ]
