# Generated by Django 2.2.5 on 2020-02-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='agg',
            new_name='age',
        ),
    ]
